apiVersion: v1
kind: Service
metadata:
{{- if .Values.carbon.service.annotations }}
  annotations:
{{ toYaml .Values.carbon.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "gographite.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.carbon.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.carbon.service.labels }}
{{ toYaml .Values.carbon.service.labels | indent 4 }}
{{- end }}
  name: {{ template "gographite.carbon.fullname" . }}
spec:
{{- if .Values.carbon.service.clusterIP }}
  clusterIP: {{ .Values.carbon.service.clusterIP }}
{{- end }}
{{- if .Values.carbon.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.carbon.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.carbon.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.carbon.service.loadBalancerIP }}
{{- end }}
{{- if .Values.carbon.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.carbon.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: carbontcp
      port: {{ .Values.carbon.service.carbontcpPort }}
      protocol: TCP
      targetPort: 2003
    - name: carbonserver
      port: {{ .Values.carbon.service.carbonserverPort }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "gographite.name" . }}
    component: "{{ .Values.carbon.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.carbon.service.type }}"
