apiVersion: extensions/v1beta1
kind: Deployment
metadata:
{{- if .Values.grafana.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.grafana.deploymentAnnotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "gographite.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.grafana.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "gographite.grafana.fullname" . }}
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  template:
    metadata:
    {{- if .Values.grafana.podAnnotations }}
      annotations:
{{ toYaml .Values.grafana.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "gographite.name" . }}
        component: "{{ .Values.grafana.name }}"
        release: {{ .Release.Name }}
{{- if .Values.grafana.pod.labels }}
{{ toYaml .Values.grafana.pod.labels | indent 8 }}
{{- end }}
    spec:
{{- if .Values.grafana.priorityClassName }}
      priorityClassName: "{{ .Values.grafana.priorityClassName }}"
{{- end }}
      containers:
        - name: {{ template "gographite.name" . }}-{{ .Values.grafana.name }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: "{{ .Values.grafana.image.pullPolicy }}"
        {{- if .Values.grafana.args }}
          args:
          {{- range $key, $value := .Values.grafana.args }}
            - --{{ $key }}={{ $value }}
          {{- end }}
        {{- end }}
          ports:
            - name: metrics
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 6
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 6
            successThreshold: 1
          resources:
{{ toYaml .Values.grafana.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /openmetric/conf/
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "gographite.grafana.fullname" . }}
    {{- if .Values.grafana.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.grafana.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.grafana.securityContext }}
      securityContext:
{{ toYaml .Values.grafana.securityContext | indent 8 }}
    {{- end }}
    {{- if .Values.grafana.tolerations }}
      tolerations:
{{ toYaml .Values.grafana.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.grafana.affinity }}
      affinity:
{{ toYaml .Values.grafana.affinity | indent 8 }}
    {{- end }}
